// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFqQxxRP3EShZ7vxO2oeDKs_O5uVyobeQ',
    appId: '1:74190012172:web:b9b4c94b901b4573735329',
    messagingSenderId: '74190012172',
    projectId: 'storeventory-f69d5',
    authDomain: 'storeventory-f69d5.firebaseapp.com',
    storageBucket: 'storeventory-f69d5.firebasestorage.app',
    measurementId: 'G-E0RTK2WX8G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDI1XeGImWDhstbjH5iw4L4eMWP05vZ3Io',
    appId: '1:74190012172:android:bb3a81527c862fd5735329',
    messagingSenderId: '74190012172',
    projectId: 'storeventory-f69d5',
    storageBucket: 'storeventory-f69d5.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC71lgC22r2EQ39b6QNBz6okEpzoyjrhnQ',
    appId: '1:74190012172:ios:e75ac6d8d5e812db735329',
    messagingSenderId: '74190012172',
    projectId: 'storeventory-f69d5',
    storageBucket: 'storeventory-f69d5.firebasestorage.app',
    iosBundleId: 'com.example.storeventory',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC71lgC22r2EQ39b6QNBz6okEpzoyjrhnQ',
    appId: '1:74190012172:ios:e75ac6d8d5e812db735329',
    messagingSenderId: '74190012172',
    projectId: 'storeventory-f69d5',
    storageBucket: 'storeventory-f69d5.firebasestorage.app',
    iosBundleId: 'com.example.storeventory',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFqQxxRP3EShZ7vxO2oeDKs_O5uVyobeQ',
    appId: '1:74190012172:web:5abe34fc0a68ae30735329',
    messagingSenderId: '74190012172',
    projectId: 'storeventory-f69d5',
    authDomain: 'storeventory-f69d5.firebaseapp.com',
    storageBucket: 'storeventory-f69d5.firebasestorage.app',
    measurementId: 'G-WSJMF03YF4',
  );
}
